import { z } from "zod";

/**
 * Outlook / recommendations contract — the SINGLE source of truth for:
 *  - the content artifact written by the (future) Aureus v2 pipeline,
 *  - the web data-access layer + UI,
 *  - the public `/api/v1` JSON consumed by the website and any future mobile app.
 *
 * The zod schema is authoritative; TS types are inferred from it. Bump
 * CONTRACT_VERSION on breaking changes and version the API route accordingly.
 */
export const CONTRACT_VERSION = 1;

export const signalSchema = z.enum(["BUY", "HOLD", "SELL"]);
export type Signal = z.infer<typeof signalSchema>;

export const confidenceSchema = z.enum(["low", "medium", "high"]);
export type Confidence = z.infer<typeof confidenceSchema>;

export const outlookCallSchema = z.object({
  /** Machine key for the horizon. */
  term: z.enum(["short", "long"]),
  /** Human label, e.g. "Short-term". */
  label: z.string().min(1),
  /** Horizon description, e.g. "Next 1–4 weeks". */
  horizon: z.string().min(1),
  signal: signalSchema,
  confidence: confidenceSchema,
  /** 2–3 sentence rationale. */
  reason: z.string().min(1),
  /** What would invalidate this view (price level / condition). */
  invalidation: z.string().optional(),
});
export type OutlookCall = z.infer<typeof outlookCallSchema>;

export const keyLevelSchema = z.object({
  label: z.string().min(1), // "Spot", "Support", "Resistance"
  value: z.string().min(1), // "$4,160"
  emphasis: z.boolean().optional(),
});
export type KeyLevel = z.infer<typeof keyLevelSchema>;

export const sourceSchema = z.object({
  title: z.string().min(1),
  url: z.string().url(),
});
export type Source = z.infer<typeof sourceSchema>;

export const spotSchema = z.object({
  price: z.number().positive(),
  currency: z.literal("USD"),
  /** ISO timestamp the spot reading is as-of. */
  asOf: z.string(),
  /** Recent change %, signed (e.g. -0.85). */
  changePct: z.number().optional(),
});
export type Spot = z.infer<typeof spotSchema>;

export const outlookReportSchema = z.object({
  contractVersion: z.literal(CONTRACT_VERSION),
  /** ISO date the view is for. */
  date: z.string(),
  /** ISO timestamp of last update. */
  updatedAt: z.string(),
  /** Editorial seed (hand-authored) vs generated by the pipeline. */
  origin: z.enum(["editorial", "generated"]),
  /** Publication state — only "published" is served publicly. */
  status: z.enum(["draft", "published"]),
  /** One-paragraph TL;DR. */
  summary: z.string().min(1),
  spot: spotSchema,
  /** Short- and long-term calls. */
  calls: z.array(outlookCallSchema).min(1),
  keyLevels: z.array(keyLevelSchema),
  /** Full analysis as Markdown (rendered safely, never as raw HTML). */
  analysisMarkdown: z.string().min(1),
  sources: z.array(sourceSchema),
});
export type OutlookReport = z.infer<typeof outlookReportSchema>;

/** Convenience accessors. */
export function shortTermCall(report: OutlookReport): OutlookCall | undefined {
  return report.calls.find((c) => c.term === "short");
}
export function longTermCall(report: OutlookReport): OutlookCall | undefined {
  return report.calls.find((c) => c.term === "long");
}
